export const TODO_GET_REQUEST = "TODO_GET_REQUEST";
export const TODO_REQUEST_SUCCESS = "TODO_REQUEST_SUCCESS";
export const TODO_POST_REQUEST = "TODO_POST_REQUEST";
export const TODO_REQUEST_FAILURE = "TODO_REQUEST_FAILURE";
export const SINGLE_TODO_GET_REQUEST = "SINGLE_TODO_GET_REQUEST";
export const SINGLE_TODO_GET_SUCCESS = "SINGLE_TODO_GET_SUCESS";
export const SINGLE_TODO_GET_FAILURE = "SINGLE_TODO_GET_FAILURE";
