export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_LOADING_SUCCESS = "COMMENTS_LOADING_SUCCESS";
export const COMMENTS_LOADING_FAILURE = "COMMENTS_LOADING_FAILURE";
export const NEW_COMMENTS_POSTING = "NEW_COMMENTS_POSTING";
export const COMMENTS_EDITING = "COMMENTS_EDITING";
export const COMMENTS_DELETING = "COMMENTS_DELETING";