export const GET_SINGLE_POST_REQUEST = 'GET_SINGLE_POST_REQUEST';
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';
export const GET_SINGLE_POST_FAILURE = 'GET_SINGLE_POST_FAILURE';
export const SINGLE_POST_EDITOR = 'SINGLE_POST_EDITOR';
export const SINGLE_POST_LIKER = 'SINGLE_POST_LIKER';

